### ISSUE TITLE
Cannot connect to Port 80

### ISSUE THREAD

**Issue by shajidmd** [tiangolo/flask-frontend-docker#3]
Thank alot for the stack,
I used this project generator and deployed it in a server as it is without changing any configurations, but after executing the deploy scripts, I see that port 80 cannot be accessed. Can you please help me out?
Attached is the screenshot of "docker ps"

Thanks
Shajid

<img width="1409" alt="Screen Shot 2019-09-25 at 5 09 48 pm" src="https://user-images.githubusercontent.com/10509763/65577563-5df72d00-dfb7-11e9-94b6-e548a825135c.png">

**Comment by shajidmd** [comment]
My bad, I had to deploy the traefik-consul stack as well. I assumed that wasn't necessary.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
